name: HideAndSeek
version: '${project.version}'
main: me.fiveship.hideandseek.HNS
api-version: 1.18
depend: [ "LibsDisguises","ProtocolLib" ]

commands:
  hns:
    description: Main command for HNS
    aliases: [ blockhunt,hideandseek,hidenseek,bh ]
  rotate:
    description: Shortcut
    aliases: [ rot,up,down,facing,bottom,top,blocks,block,spawn,spawns,seek ]